# Generated by Django 4.2 on 2023-04-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('category', models.CharField(choices=[('F', 'FASHION'), ('E', 'ELECTRONICS'), ('B', 'BAGS'), ('C', 'CLOTHES')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(default='product.jpg', upload_to='product_images')),
            ],
        ),
    ]
